Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Metrics/LineLength:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Bundler/OrderedGems:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/MixinUsage:
  Exclude:
    - 'bin/*'
